name: 🚀 Feature Request (DigiNativa AI Team)
description: Request a new feature for DigiNativa - processed by our autonomous AI development team
title: "[FEATURE] "
labels: ["enhancement", "ai-team", "dna-validation-required"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 DigiNativa AI Team Processing
        
        Your request will be autonomously processed by our specialized AI development team:
        
        1. **🎯 Project Manager** - DNA validation & story breakdown
        2. **🎨 Game Designer** - Pedagogical mechanics & UX specs (Shadcn/UI + Kenney.UI)
        3. **💻 Developer** - React+TypeScript+FastAPI implementation
        4. **🧪 Test Engineer** - Automated testing (100% coverage)
        5. **🔍 QA Tester** - Anna persona validation & accessibility
        6. **⚡ Quality Reviewer** - Performance & production readiness
        
        **All features must comply with DigiNativa's Project DNA for autonomous processing.**

  # Basic Feature Information
  - type: input
    id: feature_summary
    attributes:
      label: Feature Summary
      description: Brief, clear description of what you want
      placeholder: "Add municipal policy training module with interactive scenarios"
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Describe from the user's perspective with clear value proposition
      placeholder: "As Anna (kommunal förvaltare), I want to practice applying new digital policies in realistic scenarios so that I can confidently implement them in my daily work without making costly mistakes..."
      value: "As [specific user persona], I want [specific functionality] so that [clear measurable benefit/outcome]..."
    validations:
      required: true

  # DNA Compliance Section (Critical)
  - type: markdown
    attributes:
      value: |
        ---
        ## 🧬 PROJECT DNA COMPLIANCE (REQUIRED)
        
        **All features MUST align with DigiNativa's Project DNA to be processed by the AI team.**

  - type: checkboxes
    id: design_principles
    attributes:
      label: Design Principles Alignment (5 Core Principles)
      description: "Select ALL principles this feature supports. Features must support at least 3 principles for AI processing."
      options:
        - label: "🎓 **Pedagogik Framför Allt** - Serves clear educational goals about digitalization strategy"
        - label: "🌉 **Policy till Praktik** - Bridges abstract policy concepts to practical implementation"
        - label: "⏰ **Respekt för Tid** - Respects busy schedules (≤10 minute learning sessions)"
        - label: "🔗 **Helhetssyn** - Shows system connections and holistic thinking"
        - label: "🎯 **Intelligens, Inte Infantilisering** - Professional tone and sophisticated approach"
    validations:
      required: true

  - type: checkboxes
    id: architecture_principles
    attributes:
      label: Architecture Principles Compliance (4 Core Principles)
      description: "Confirm this feature aligns with our technical architecture. AI team will validate during implementation."
      options:
        - label: "🔌 **API-First Design** - All functionality accessible via REST APIs"
        - label: "🚫 **Stateless Backend** - No server-side sessions, all state from client"
        - label: "🎯 **Separation of Concerns** - Frontend and backend remain completely separate"
        - label: "💎 **Simplicity First** - Choose simplest solution that works"
    validations:
      required: true

  # Municipal Context (Critical for Swedish Public Sector)
  - type: markdown
    attributes:
      value: |
        ---
        ## 🏛️ MUNICIPAL CONTEXT

  - type: dropdown
    id: target_audience
    attributes:
      label: Primary Target Persona
      description: "Which specific DigiNativa persona is this for?"
      options:
        - Anna (Offentlig förvaltare - primary learning persona)
        - Erik (IT-chef - technical implementation lead)  
        - Margareta (Kommunchef - strategic decision maker)
        - David (Handläggare - frontline service delivery)
        - System administrators
        - Other (specify in Municipal Use Case)
    validations:
      required: true

  - type: dropdown
    id: municipal_department
    attributes:
      label: Municipal Department Focus
      description: "Which department/area will primarily use this feature?"
      options:
        - Kommunledning (Municipal management)
        - IT-avdelning (IT department)
        - HR/Personalavdelning (Human resources)
        - Medborgarservice (Citizen services)
        - Ekonomiavdelning (Finance department)
        - Teknik och miljö (Technical & environmental)
        - Utbildning (Education)
        - Vård och omsorg (Healthcare & elderly care)
        - Kultur och fritid (Culture & leisure)
        - Cross-departmental
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: municipal_use_case
    attributes:
      label: Municipal Use Case & Policy Alignment
      description: "Describe the specific municipal context and how this aligns with digitalization policies"
      placeholder: |
        **Municipal Process:** Which processes/workflows does this support?
        **Policy Alignment:** How does this align with Swedish digitalization initiatives?
        **Expected Impact:** What impact on municipal efficiency/citizen service?
      value: |
        **Municipal Process:** 
        **Policy Alignment:** 
        **Expected Impact:** 
    validations:
      required: true

  # Learning Objectives (Critical for Pedagogical Success)
  - type: markdown
    attributes:
      value: |
        ---
        ## 🎓 LEARNING OBJECTIVES

  - type: checkboxes
    id: learning_objectives
    attributes:
      label: Learning Objectives (Check all that apply)
      description: "What should users learn/achieve through this feature?"
      options:
        - label: "📋 **Policy Understanding** - Comprehend new digitalization policies"
        - label: "🔧 **Practical Application** - Apply policies to real work scenarios" 
        - label: "🤝 **Stakeholder Engagement** - Improve collaboration across departments"
        - label: "📊 **Data-Driven Decisions** - Use data to inform municipal decisions"
        - label: "🛡️ **Risk Management** - Identify and mitigate digitalization risks"
        - label: "🎯 **Strategic Thinking** - Understand long-term digital transformation"
        - label: "💡 **Innovation Mindset** - Embrace new digital solutions"
        - label: "👥 **Change Management** - Lead organizational digital change"
        - label: "🔒 **Security Awareness** - Understand digital security requirements"
        - label: "📈 **Performance Measurement** - Track and evaluate digital initiatives"
    validations:
      required: true

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics & Measurement
      description: "How will we measure if this feature achieves its learning objectives?"
      placeholder: |
        **Completion Rate Target:** (e.g., >90% completion)
        **Satisfaction Score Target:** (e.g., >4.5/5)
        **Knowledge Retention Measure:** (e.g., post-training assessments)
        **Behavioral Impact Expected:** (e.g., policy implementation rate)
      value: |
        **Completion Rate Target:** 
        **Satisfaction Score Target:** 
        **Knowledge Retention Measure:** 
        **Behavioral Impact Expected:** 
    validations:
      required: true

  # Time Constraints (Critical for DNA Compliance)
  - type: markdown
    attributes:
      value: |
        ---
        ## ⏰ TIME CONSTRAINTS

  - type: dropdown
    id: max_completion_time
    attributes:
      label: Maximum Completion Time
      description: "What's the maximum time a user should spend on this feature? (DNA Principle: Respekt för Tid)"
      options:
        - "2 minutes (micro-learning)"
        - "5 minutes (quick task)"
        - "10 minutes (standard session - RECOMMENDED)"
        - "15 minutes (complex topic - requires justification)"
        - "20+ minutes (exceptional cases only - requires approval)"
    validations:
      required: true

  - type: input
    id: target_completion_time
    attributes:
      label: Target Completion Time
      description: "Ideal time for most users to complete this feature"
      placeholder: "7 minutes"
    validations:
      required: true

  # Detailed Requirements
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (Detailed)
      description: "Specific, testable criteria for completion. AI team uses these for validation. MAXIMUM 5 criteria for DNA compliance."
      placeholder: |
        - [ ] User can access new feature from main navigation
        - [ ] Feature loads within 2 seconds on standard broadband
        - [ ] All text content is available in Swedish
        - [ ] Feature works correctly on desktop, tablet, and mobile
        - [ ] Accessibility: All interactive elements keyboard accessible
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  # Technical Specifications (AI Team Ready)
  - type: checkboxes
    id: technical_requirements
    attributes:
      label: Technical Requirements (AI Team Will Implement)
      description: "Select applicable technical requirements"
      options:
        - label: "⚛️ **React Components** - Custom UI components needed"
        - label: "🎨 **Shadcn/UI Integration** - Use existing component library"
        - label: "🎮 **Kenney.UI Assets** - Game-style visual elements needed"
        - label: "🔌 **API Endpoints** - New backend functionality required"
        - label: "💾 **Database Changes** - Data model modifications needed"
        - label: "📱 **Mobile Responsive** - Must work on mobile devices"
        - label: "♿ **Accessibility (WCAG AA)** - Screen reader & keyboard navigation"
        - label: "🌐 **Multi-language Support** - Swedish + English support"
        - label: "📊 **Analytics Integration** - Usage tracking and metrics"
        - label: "🔒 **Authentication Required** - User login needed"

  - type: checkboxes
    id: performance_requirements
    attributes:
      label: Performance Requirements (Non-Negotiable)
      description: "These are automatically validated by the AI team"
      options:
        - label: "⚡ **API Response Time** - All endpoints must respond <200ms"
        - label: "🚀 **Lighthouse Score** - Performance score >90"
        - label: "📦 **Bundle Size** - Keep JavaScript bundle impact minimal"
        - label: "📱 **Mobile Performance** - Smooth operation on mobile devices"
        - label: "🔧 **TypeScript Compliance** - Zero TypeScript errors"
        - label: "✅ **Test Coverage** - 100% code coverage required"

  # Implementation Planning
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Implementation Complexity
      description: "AI team will validate this assessment"
      options:
        - Simple (1-2 components, minimal logic) - 2-4 hours
        - Medium (multiple components, moderate logic) - 1-2 days  
        - Complex (system integration, advanced logic) - 3-5 days
        - Very Complex (major feature, multiple systems) - 1-2 weeks
        - Unknown (requires analysis)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority Level
      description: "How urgent is this feature for DigiNativa's success?"
      options:
        - P0 - Critical (blocking other work/users)
        - P1 - High (key business value, current focus area) 
        - P2 - Medium (valuable but can wait)
        - P3 - Low (nice to have, future consideration)
    validations:
      required: true

  # Additional Context
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context & Resources
      description: "Screenshots, mockups, research, related issues, or other helpful information"
      placeholder: |
        **Visual References:** (screenshots, mockups, design inspiration)
        **Related Research:** (user studies, policy documents, best practices)
        **Similar Features:** (examples from other systems)
        **Related Issues:** (#123, #124)

  # Process Information
  - type: markdown
    attributes:
      value: |
        ---
        ## 🔄 WHAT HAPPENS NEXT?
        
        ### Autonomous AI Development Process:
        
        1. **📋 Project Manager Analysis** (Within 4 hours)
           - DNA compliance validation
           - Story breakdown creation  
           - Agent assignment optimization
        
        2. **🎨 Game Designer Specification** (4-8 hours)
           - Pedagogical game mechanics design
           - UX specifications with Shadcn/UI components
           - Wireframes and interaction flows
        
        3. **💻 Developer Implementation** (1-5 days based on complexity)
           - React+TypeScript frontend development
           - FastAPI backend implementation
           - Git operations and branch management
        
        4. **🧪 Test Engineer Validation** (2-6 hours)
           - 100% automated test coverage
           - Performance benchmarking
           - Security vulnerability scanning
        
        5. **🔍 QA Tester Experience Validation** (2-4 hours)
           - Anna persona testing simulation
           - Accessibility compliance (WCAG AA)
           - User flow optimization
        
        6. **⚡ Quality Reviewer Final Approval** (1-2 hours)
           - Production readiness validation
           - Performance metrics confirmation
           - Deployment approval
        
        ### Timeline Estimates:
        - **Simple Features:** 1-2 days end-to-end
        - **Medium Features:** 3-5 days end-to-end  
        - **Complex Features:** 1-2 weeks end-to-end
        
        **Your feature will be ready for testing in the preview environment once all quality gates pass!** 🚀